skip_tags: true

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

os: Visual Studio 2015

environment:
  matrix:
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
    - PYTHON: C:\Python37-x64
  PYPI_PASSWORD:
    secure: YFdsigZEYNmPA6dCIKuIV4d1T1YMI8YtNHolln9MypY=

build_script:
  - choco install winfsp -y --version=1.4.19016
  - git --no-pager log -n2
  - echo %APPVEYOR_REPO_COMMIT%
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;;%PATH%
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - python -m pip install --upgrade pip
  - pip install -r requirements-dev.txt
  - pip install .

test_script:
  # Uncomment this for RDP debug
  # - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
  # Only print output if check failed
  - black setup.py tests src --check
  - py.test tests/ -vvv

after_test:
  - python setup.py bdist_wheel

artifacts:
  path: 'dist/*.whl'

deploy_script:
  - echo "Starting Artifact Deployment"
  # populate pypirc file for twine
  - echo [distutils]                                  > %USERPROFILE%\\.pypirc
  - echo index-servers =                             >> %USERPROFILE%\\.pypirc
  - echo     pypi                                    >> %USERPROFILE%\\.pypirc
  - echo [pypi]                                      >> %USERPROFILE%\\.pypirc
  - echo username=touilleMan                         >> %USERPROFILE%\\.pypirc
  - echo password=%PYPI_PASSWORD%                    >> %USERPROFILE%\\.pypirc
  # upload to pypi for windows
  - set PATH=%BK_PATH%
  - set HOME=%USERPROFILE%
  - ps: If ($env:APPVEYOR_REPO_TAG -eq "true" -And $env:APPVEYOR_REPO_BRANCH -eq "master") { Invoke-Expression "twine upload --skip-existing dist/*.whl" 2>$null } Else { write-output "Not on a tag on master, won't deploy to pypi"}
  - echo "Finished Artifact Deployment"
