repos:
-   repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
    - id: black
      args:
          - "--line-length=100"
      language_version: python3
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      args:
        - "--max-line-length=100"
        - "--ignore=E203,E266,E501,W503"
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0  # Use the ref you want to point at
    hooks:
    - id: mixed-line-ending
      args:
        - "--fix=lf"
    - id: trailing-whitespace
